# Generated by Django 5.0.2 on 2024-03-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='travelPoints',
        ),
    ]
