# Generated by Django 5.0.2 on 2024-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_App', '0002_remove_passenger_travelpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='booking_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
